// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID             pgtype.UUID
	ClientID       string
	TaskType       string
	Payload        []byte
	State          string
	RunAt          pgtype.Timestamptz
	WorkerID       pgtype.Text
	Result         []byte
	RetryCount     int32
	MaxRetries     int32
	TimeoutSeconds int32
	LastFailedAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ErrorMessage   string
	Version        int32
}

type TaskEvent struct {
	EventID       int64
	OccurredAt    pgtype.Timestamptz
	EventType     string
	TaskID        string
	PreviousState string
	CurrentState  string
	TaskVersion   int64
	WorkerID      string
	Reason        string
}

type TaskLog struct {
	Sequence  int64
	TaskID    string
	Timestamp pgtype.Timestamptz
	Level     string
	Component string
	Message   string
	Fields    []byte
}
