// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID             pgtype.UUID
	ClientID       string
	TaskType       string
	Payload        []byte
	State          string
	RunAt          pgtype.Timestamptz
	WorkerID       pgtype.Text
	Result         []byte
	RetryCount     int32
	MaxRetries     int32
	TimeoutSeconds int32
	LastFailedAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
