// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (
    id, client_id, task_type, payload, state, run_at, 
    worker_id, result, retry_count, max_retries, 
    timeout_seconds, last_failed_at, created_at, updated_at, error_message, version
) VALUES (
    $1, $2, $3, $4, $5, $6, 
    $7, $8, $9, $10, 
    $11, $12, $13, $14, $15, $16
)
`

type CreateTaskParams struct {
	ID             pgtype.UUID
	ClientID       string
	TaskType       string
	Payload        []byte
	State          string
	RunAt          pgtype.Timestamptz
	WorkerID       pgtype.Text
	Result         []byte
	RetryCount     int32
	MaxRetries     int32
	TimeoutSeconds int32
	LastFailedAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ErrorMessage   string
	Version        int32
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.Exec(ctx, createTask,
		arg.ID,
		arg.ClientID,
		arg.TaskType,
		arg.Payload,
		arg.State,
		arg.RunAt,
		arg.WorkerID,
		arg.Result,
		arg.RetryCount,
		arg.MaxRetries,
		arg.TimeoutSeconds,
		arg.LastFailedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ErrorMessage,
		arg.Version,
	)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, client_id, task_type, payload, state, run_at, worker_id, result, retry_count, max_retries, timeout_seconds, last_failed_at, created_at, updated_at, error_message, version FROM tasks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TaskType,
		&i.Payload,
		&i.State,
		&i.RunAt,
		&i.WorkerID,
		&i.Result,
		&i.RetryCount,
		&i.MaxRetries,
		&i.TimeoutSeconds,
		&i.LastFailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ErrorMessage,
		&i.Version,
	)
	return i, err
}

const listEligibleTasks = `-- name: ListEligibleTasks :many
SELECT id, client_id, task_type, payload, state, run_at, worker_id, result, retry_count, max_retries, timeout_seconds, last_failed_at, created_at, updated_at, error_message, version FROM tasks
WHERE state = 'PENDING'
  AND run_at <= $1
ORDER BY run_at ASC
LIMIT $2
`

type ListEligibleTasksParams struct {
	RunAt pgtype.Timestamptz
	Limit int32
}

func (q *Queries) ListEligibleTasks(ctx context.Context, arg ListEligibleTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listEligibleTasks, arg.RunAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.TaskType,
			&i.Payload,
			&i.State,
			&i.RunAt,
			&i.WorkerID,
			&i.Result,
			&i.RetryCount,
			&i.MaxRetries,
			&i.TimeoutSeconds,
			&i.LastFailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ErrorMessage,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseTasks = `-- name: ReleaseTasks :exec
UPDATE tasks
SET 
    state = 'PENDING',
    worker_id = NULL,
    version = version + 1,
    updated_at = NOW()
WHERE worker_id = $1 
  AND state IN ('RUNNING', 'SCHEDULED')
`

func (q *Queries) ReleaseTasks(ctx context.Context, workerID pgtype.Text) error {
	_, err := q.db.Exec(ctx, releaseTasks, workerID)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks
SET 
    state = $2,
    worker_id = $3,
    result = $4,
    retry_count = $5,
    last_failed_at = $6,
    run_at = $7,
    updated_at = NOW(),
 error_message = $8,
 version = $9,
 max_retries = $10
WHERE id = $1
`

type UpdateTaskParams struct {
	ID           pgtype.UUID
	State        string
	WorkerID     pgtype.Text
	Result       []byte
	RetryCount   int32
	LastFailedAt pgtype.Timestamptz
	RunAt        pgtype.Timestamptz
	ErrorMessage string
	Version      int32
	MaxRetries   int32
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.Exec(ctx, updateTask,
		arg.ID,
		arg.State,
		arg.WorkerID,
		arg.Result,
		arg.RetryCount,
		arg.LastFailedAt,
		arg.RunAt,
		arg.ErrorMessage,
		arg.Version,
		arg.MaxRetries,
	)
	return err
}
