// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/orchestrator/v1/control_plane.proto

package orchestratorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	TaskState_TASK_STATE_PENDING     TaskState = 1
	TaskState_TASK_STATE_SCHEDULED   TaskState = 2
	TaskState_TASK_STATE_RUNNING     TaskState = 3
	TaskState_TASK_STATE_COMPLETED   TaskState = 4
	TaskState_TASK_STATE_FAILED      TaskState = 5
	TaskState_TASK_STATE_CANCELLED   TaskState = 6
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "TASK_STATE_PENDING",
		2: "TASK_STATE_SCHEDULED",
		3: "TASK_STATE_RUNNING",
		4: "TASK_STATE_COMPLETED",
		5: "TASK_STATE_FAILED",
		6: "TASK_STATE_CANCELLED",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED": 0,
		"TASK_STATE_PENDING":     1,
		"TASK_STATE_SCHEDULED":   2,
		"TASK_STATE_RUNNING":     3,
		"TASK_STATE_COMPLETED":   4,
		"TASK_STATE_FAILED":      5,
		"TASK_STATE_CANCELLED":   6,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_orchestrator_v1_control_plane_proto_enumTypes[0].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_api_proto_orchestrator_v1_control_plane_proto_enumTypes[0]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{0}
}

type TaskSortField int32

const (
	TaskSortField_TASK_SORT_FIELD_UNSPECIFIED TaskSortField = 0
	TaskSortField_TASK_SORT_FIELD_CREATED_AT  TaskSortField = 1
	TaskSortField_TASK_SORT_FIELD_UPDATED_AT  TaskSortField = 2
	TaskSortField_TASK_SORT_FIELD_RUN_AT      TaskSortField = 3
)

// Enum value maps for TaskSortField.
var (
	TaskSortField_name = map[int32]string{
		0: "TASK_SORT_FIELD_UNSPECIFIED",
		1: "TASK_SORT_FIELD_CREATED_AT",
		2: "TASK_SORT_FIELD_UPDATED_AT",
		3: "TASK_SORT_FIELD_RUN_AT",
	}
	TaskSortField_value = map[string]int32{
		"TASK_SORT_FIELD_UNSPECIFIED": 0,
		"TASK_SORT_FIELD_CREATED_AT":  1,
		"TASK_SORT_FIELD_UPDATED_AT":  2,
		"TASK_SORT_FIELD_RUN_AT":      3,
	}
)

func (x TaskSortField) Enum() *TaskSortField {
	p := new(TaskSortField)
	*p = x
	return p
}

func (x TaskSortField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskSortField) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_orchestrator_v1_control_plane_proto_enumTypes[1].Descriptor()
}

func (TaskSortField) Type() protoreflect.EnumType {
	return &file_api_proto_orchestrator_v1_control_plane_proto_enumTypes[1]
}

func (x TaskSortField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskSortField.Descriptor instead.
func (TaskSortField) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{1}
}

type SortDirection int32

const (
	SortDirection_SORT_DIRECTION_UNSPECIFIED SortDirection = 0
	SortDirection_SORT_DIRECTION_ASC         SortDirection = 1
	SortDirection_SORT_DIRECTION_DESC        SortDirection = 2
)

// Enum value maps for SortDirection.
var (
	SortDirection_name = map[int32]string{
		0: "SORT_DIRECTION_UNSPECIFIED",
		1: "SORT_DIRECTION_ASC",
		2: "SORT_DIRECTION_DESC",
	}
	SortDirection_value = map[string]int32{
		"SORT_DIRECTION_UNSPECIFIED": 0,
		"SORT_DIRECTION_ASC":         1,
		"SORT_DIRECTION_DESC":        2,
	}
)

func (x SortDirection) Enum() *SortDirection {
	p := new(SortDirection)
	*p = x
	return p
}

func (x SortDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_orchestrator_v1_control_plane_proto_enumTypes[2].Descriptor()
}

func (SortDirection) Type() protoreflect.EnumType {
	return &file_api_proto_orchestrator_v1_control_plane_proto_enumTypes[2]
}

func (x SortDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortDirection.Descriptor instead.
func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{2}
}

type TaskEventType int32

const (
	TaskEventType_TASK_EVENT_TYPE_UNSPECIFIED        TaskEventType = 0
	TaskEventType_TASK_EVENT_TYPE_CREATED            TaskEventType = 1
	TaskEventType_TASK_EVENT_TYPE_STATE_CHANGED      TaskEventType = 2
	TaskEventType_TASK_EVENT_TYPE_RETRIED            TaskEventType = 3
	TaskEventType_TASK_EVENT_TYPE_CANCEL_REQUESTED   TaskEventType = 4
	TaskEventType_TASK_EVENT_TYPE_ASSIGNMENT_CHANGED TaskEventType = 5
	TaskEventType_TASK_EVENT_TYPE_HEARTBEAT          TaskEventType = 6
)

// Enum value maps for TaskEventType.
var (
	TaskEventType_name = map[int32]string{
		0: "TASK_EVENT_TYPE_UNSPECIFIED",
		1: "TASK_EVENT_TYPE_CREATED",
		2: "TASK_EVENT_TYPE_STATE_CHANGED",
		3: "TASK_EVENT_TYPE_RETRIED",
		4: "TASK_EVENT_TYPE_CANCEL_REQUESTED",
		5: "TASK_EVENT_TYPE_ASSIGNMENT_CHANGED",
		6: "TASK_EVENT_TYPE_HEARTBEAT",
	}
	TaskEventType_value = map[string]int32{
		"TASK_EVENT_TYPE_UNSPECIFIED":        0,
		"TASK_EVENT_TYPE_CREATED":            1,
		"TASK_EVENT_TYPE_STATE_CHANGED":      2,
		"TASK_EVENT_TYPE_RETRIED":            3,
		"TASK_EVENT_TYPE_CANCEL_REQUESTED":   4,
		"TASK_EVENT_TYPE_ASSIGNMENT_CHANGED": 5,
		"TASK_EVENT_TYPE_HEARTBEAT":          6,
	}
)

func (x TaskEventType) Enum() *TaskEventType {
	p := new(TaskEventType)
	*p = x
	return p
}

func (x TaskEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_orchestrator_v1_control_plane_proto_enumTypes[3].Descriptor()
}

func (TaskEventType) Type() protoreflect.EnumType {
	return &file_api_proto_orchestrator_v1_control_plane_proto_enumTypes[3]
}

func (x TaskEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskEventType.Descriptor instead.
func (TaskEventType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{3}
}

type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARN        LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARN",
		4: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARN":        3,
		"LOG_LEVEL_ERROR":       4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_orchestrator_v1_control_plane_proto_enumTypes[4].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_api_proto_orchestrator_v1_control_plane_proto_enumTypes[4]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{4}
}

type Scope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	NamespaceId   string                 `protobuf:"bytes,2,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{0}
}

func (x *Scope) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Scope) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{1}
}

func (x *TimeRange) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TimeRange) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType      string                 `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	State         TaskState              `protobuf:"varint,4,opt,name=state,proto3,enum=orchestrator.v1.TaskState" json:"state,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Result        []byte                 `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	WorkerId      string                 `protobuf:"bytes,7,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	RetryCount    int32                  `protobuf:"varint,8,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,9,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	RunAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=run_at,json=runAt,proto3" json:"run_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastFailedAt  *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=last_failed_at,json=lastFailedAt,proto3" json:"last_failed_at,omitempty"`
	Version       int64                  `protobuf:"varint,14,opt,name=version,proto3" json:"version,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,15,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,16,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{2}
}

func (x *Task) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *Task) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *Task) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Task) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Task) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Task) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Task) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *Task) GetRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RunAt
	}
	return nil
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Task) GetLastFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastFailedAt
	}
	return nil
}

func (x *Task) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Task) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Task) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type TaskFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	States        []TaskState            `protobuf:"varint,1,rep,packed,name=states,proto3,enum=orchestrator.v1.TaskState" json:"states,omitempty"`
	TaskTypes     []string               `protobuf:"bytes,2,rep,name=task_types,json=taskTypes,proto3" json:"task_types,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskIdPrefix  string                 `protobuf:"bytes,4,opt,name=task_id_prefix,json=taskIdPrefix,proto3" json:"task_id_prefix,omitempty"`
	CreatedAt     *TimeRange             `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *TimeRange             `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	RunAt         *TimeRange             `protobuf:"bytes,7,opt,name=run_at,json=runAt,proto3" json:"run_at,omitempty"`
	TextQuery     string                 `protobuf:"bytes,8,opt,name=text_query,json=textQuery,proto3" json:"text_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskFilter) Reset() {
	*x = TaskFilter{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskFilter) ProtoMessage() {}

func (x *TaskFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskFilter.ProtoReflect.Descriptor instead.
func (*TaskFilter) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{3}
}

func (x *TaskFilter) GetStates() []TaskState {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *TaskFilter) GetTaskTypes() []string {
	if x != nil {
		return x.TaskTypes
	}
	return nil
}

func (x *TaskFilter) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskFilter) GetTaskIdPrefix() string {
	if x != nil {
		return x.TaskIdPrefix
	}
	return ""
}

func (x *TaskFilter) GetCreatedAt() *TimeRange {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TaskFilter) GetUpdatedAt() *TimeRange {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TaskFilter) GetRunAt() *TimeRange {
	if x != nil {
		return x.RunAt
	}
	return nil
}

func (x *TaskFilter) GetTextQuery() string {
	if x != nil {
		return x.TextQuery
	}
	return ""
}

type TaskSort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         TaskSortField          `protobuf:"varint,1,opt,name=field,proto3,enum=orchestrator.v1.TaskSortField" json:"field,omitempty"`
	Direction     SortDirection          `protobuf:"varint,2,opt,name=direction,proto3,enum=orchestrator.v1.SortDirection" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSort) Reset() {
	*x = TaskSort{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSort) ProtoMessage() {}

func (x *TaskSort) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSort.ProtoReflect.Descriptor instead.
func (*TaskSort) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{4}
}

func (x *TaskSort) GetField() TaskSortField {
	if x != nil {
		return x.Field
	}
	return TaskSortField_TASK_SORT_FIELD_UNSPECIFIED
}

func (x *TaskSort) GetDirection() SortDirection {
	if x != nil {
		return x.Direction
	}
	return SortDirection_SORT_DIRECTION_UNSPECIFIED
}

type ListTasksRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Scope          *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	PageSize       int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Cursor         string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Filter         *TaskFilter            `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	Sort           *TaskSort              `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	IncludePayload bool                   `protobuf:"varint,6,opt,name=include_payload,json=includePayload,proto3" json:"include_payload,omitempty"`
	IncludeResult  bool                   `protobuf:"varint,7,opt,name=include_result,json=includeResult,proto3" json:"include_result,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{5}
}

func (x *ListTasksRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *ListTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTasksRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListTasksRequest) GetFilter() *TaskFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListTasksRequest) GetSort() *TaskSort {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *ListTasksRequest) GetIncludePayload() bool {
	if x != nil {
		return x.IncludePayload
	}
	return false
}

func (x *ListTasksRequest) GetIncludeResult() bool {
	if x != nil {
		return x.IncludeResult
	}
	return false
}

type ListTasksResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Tasks           []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	NextCursor      string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore         bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	SnapshotTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=snapshot_time,json=snapshotTime,proto3" json:"snapshot_time,omitempty"`
	SnapshotEventId int64                  `protobuf:"varint,5,opt,name=snapshot_event_id,json=snapshotEventId,proto3" json:"snapshot_event_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{6}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListTasksResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ListTasksResponse) GetSnapshotTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SnapshotTime
	}
	return nil
}

func (x *ListTasksResponse) GetSnapshotEventId() int64 {
	if x != nil {
		return x.SnapshotEventId
	}
	return 0
}

type GetTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Scope          *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	TaskId         string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	IncludePayload bool                   `protobuf:"varint,3,opt,name=include_payload,json=includePayload,proto3" json:"include_payload,omitempty"`
	IncludeResult  bool                   `protobuf:"varint,4,opt,name=include_result,json=includeResult,proto3" json:"include_result,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{7}
}

func (x *GetTaskRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskRequest) GetIncludePayload() bool {
	if x != nil {
		return x.IncludePayload
	}
	return false
}

func (x *GetTaskRequest) GetIncludeResult() bool {
	if x != nil {
		return x.IncludeResult
	}
	return false
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{8}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type TaskEventFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	States        []TaskState            `protobuf:"varint,1,rep,packed,name=states,proto3,enum=orchestrator.v1.TaskState" json:"states,omitempty"`
	TaskTypes     []string               `protobuf:"bytes,2,rep,name=task_types,json=taskTypes,proto3" json:"task_types,omitempty"`
	TaskIds       []string               `protobuf:"bytes,3,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	WorkerId      string                 `protobuf:"bytes,4,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEventFilter) Reset() {
	*x = TaskEventFilter{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEventFilter) ProtoMessage() {}

func (x *TaskEventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEventFilter.ProtoReflect.Descriptor instead.
func (*TaskEventFilter) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{9}
}

func (x *TaskEventFilter) GetStates() []TaskState {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *TaskEventFilter) GetTaskTypes() []string {
	if x != nil {
		return x.TaskTypes
	}
	return nil
}

func (x *TaskEventFilter) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

func (x *TaskEventFilter) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type StreamTaskEventsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Scope  *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Filter *TaskEventFilter       `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	// Types that are valid to be assigned to ResumePosition:
	//
	//	*StreamTaskEventsRequest_ResumeToken
	//	*StreamTaskEventsRequest_AfterEventId
	ResumePosition         isStreamTaskEventsRequest_ResumePosition `protobuf_oneof:"resume_position"`
	MaxBatchSize           int32                                    `protobuf:"varint,5,opt,name=max_batch_size,json=maxBatchSize,proto3" json:"max_batch_size,omitempty"`
	IncludeCurrentSnapshot bool                                     `protobuf:"varint,6,opt,name=include_current_snapshot,json=includeCurrentSnapshot,proto3" json:"include_current_snapshot,omitempty"`
	IncludeTaskSnapshot    bool                                     `protobuf:"varint,7,opt,name=include_task_snapshot,json=includeTaskSnapshot,proto3" json:"include_task_snapshot,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StreamTaskEventsRequest) Reset() {
	*x = StreamTaskEventsRequest{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTaskEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTaskEventsRequest) ProtoMessage() {}

func (x *StreamTaskEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTaskEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamTaskEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{10}
}

func (x *StreamTaskEventsRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *StreamTaskEventsRequest) GetFilter() *TaskEventFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *StreamTaskEventsRequest) GetResumePosition() isStreamTaskEventsRequest_ResumePosition {
	if x != nil {
		return x.ResumePosition
	}
	return nil
}

func (x *StreamTaskEventsRequest) GetResumeToken() string {
	if x != nil {
		if x, ok := x.ResumePosition.(*StreamTaskEventsRequest_ResumeToken); ok {
			return x.ResumeToken
		}
	}
	return ""
}

func (x *StreamTaskEventsRequest) GetAfterEventId() int64 {
	if x != nil {
		if x, ok := x.ResumePosition.(*StreamTaskEventsRequest_AfterEventId); ok {
			return x.AfterEventId
		}
	}
	return 0
}

func (x *StreamTaskEventsRequest) GetMaxBatchSize() int32 {
	if x != nil {
		return x.MaxBatchSize
	}
	return 0
}

func (x *StreamTaskEventsRequest) GetIncludeCurrentSnapshot() bool {
	if x != nil {
		return x.IncludeCurrentSnapshot
	}
	return false
}

func (x *StreamTaskEventsRequest) GetIncludeTaskSnapshot() bool {
	if x != nil {
		return x.IncludeTaskSnapshot
	}
	return false
}

type isStreamTaskEventsRequest_ResumePosition interface {
	isStreamTaskEventsRequest_ResumePosition()
}

type StreamTaskEventsRequest_ResumeToken struct {
	ResumeToken string `protobuf:"bytes,3,opt,name=resume_token,json=resumeToken,proto3,oneof"`
}

type StreamTaskEventsRequest_AfterEventId struct {
	AfterEventId int64 `protobuf:"varint,4,opt,name=after_event_id,json=afterEventId,proto3,oneof"`
}

func (*StreamTaskEventsRequest_ResumeToken) isStreamTaskEventsRequest_ResumePosition() {}

func (*StreamTaskEventsRequest_AfterEventId) isStreamTaskEventsRequest_ResumePosition() {}

type TaskEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	EventType     TaskEventType          `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=orchestrator.v1.TaskEventType" json:"event_type,omitempty"`
	Scope         *Scope                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	TaskId        string                 `protobuf:"bytes,5,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	PreviousState TaskState              `protobuf:"varint,6,opt,name=previous_state,json=previousState,proto3,enum=orchestrator.v1.TaskState" json:"previous_state,omitempty"`
	CurrentState  TaskState              `protobuf:"varint,7,opt,name=current_state,json=currentState,proto3,enum=orchestrator.v1.TaskState" json:"current_state,omitempty"`
	TaskVersion   int64                  `protobuf:"varint,8,opt,name=task_version,json=taskVersion,proto3" json:"task_version,omitempty"`
	WorkerId      string                 `protobuf:"bytes,9,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Reason        string                 `protobuf:"bytes,10,opt,name=reason,proto3" json:"reason,omitempty"`
	TaskSnapshot  *Task                  `protobuf:"bytes,11,opt,name=task_snapshot,json=taskSnapshot,proto3" json:"task_snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{11}
}

func (x *TaskEvent) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *TaskEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *TaskEvent) GetEventType() TaskEventType {
	if x != nil {
		return x.EventType
	}
	return TaskEventType_TASK_EVENT_TYPE_UNSPECIFIED
}

func (x *TaskEvent) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *TaskEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskEvent) GetPreviousState() TaskState {
	if x != nil {
		return x.PreviousState
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *TaskEvent) GetCurrentState() TaskState {
	if x != nil {
		return x.CurrentState
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *TaskEvent) GetTaskVersion() int64 {
	if x != nil {
		return x.TaskVersion
	}
	return 0
}

func (x *TaskEvent) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TaskEvent) GetTaskSnapshot() *Task {
	if x != nil {
		return x.TaskSnapshot
	}
	return nil
}

type StreamTaskEventsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Events               []*TaskEvent           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextResumeToken      string                 `protobuf:"bytes,2,opt,name=next_resume_token,json=nextResumeToken,proto3" json:"next_resume_token,omitempty"`
	HighWatermarkEventId int64                  `protobuf:"varint,3,opt,name=high_watermark_event_id,json=highWatermarkEventId,proto3" json:"high_watermark_event_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StreamTaskEventsResponse) Reset() {
	*x = StreamTaskEventsResponse{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTaskEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTaskEventsResponse) ProtoMessage() {}

func (x *StreamTaskEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTaskEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamTaskEventsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{12}
}

func (x *StreamTaskEventsResponse) GetEvents() []*TaskEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *StreamTaskEventsResponse) GetNextResumeToken() string {
	if x != nil {
		return x.NextResumeToken
	}
	return ""
}

func (x *StreamTaskEventsResponse) GetHighWatermarkEventId() int64 {
	if x != nil {
		return x.HighWatermarkEventId
	}
	return 0
}

type CancelTaskRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Scope           *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	TaskId          string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestId       string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,5,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{13}
}

func (x *CancelTaskRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CancelTaskRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CancelTaskRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type CancelTaskResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Task            *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Accepted        bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	AlreadyTerminal bool                   `protobuf:"varint,3,opt,name=already_terminal,json=alreadyTerminal,proto3" json:"already_terminal,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{14}
}

func (x *CancelTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *CancelTaskResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *CancelTaskResponse) GetAlreadyTerminal() bool {
	if x != nil {
		return x.AlreadyTerminal
	}
	return false
}

type RetryTaskRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Scope           *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	TaskId          string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	RunAtOverride   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=run_at_override,json=runAtOverride,proto3" json:"run_at_override,omitempty"`
	RequestId       string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,6,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RetryTaskRequest) Reset() {
	*x = RetryTaskRequest{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryTaskRequest) ProtoMessage() {}

func (x *RetryTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryTaskRequest.ProtoReflect.Descriptor instead.
func (*RetryTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{15}
}

func (x *RetryTaskRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *RetryTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RetryTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RetryTaskRequest) GetRunAtOverride() *timestamppb.Timestamp {
	if x != nil {
		return x.RunAtOverride
	}
	return nil
}

func (x *RetryTaskRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RetryTaskRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type RetryTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryTaskResponse) Reset() {
	*x = RetryTaskResponse{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryTaskResponse) ProtoMessage() {}

func (x *RetryTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryTaskResponse.ProtoReflect.Descriptor instead.
func (*RetryTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{16}
}

func (x *RetryTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *RetryTaskResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type GetClusterStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Window        *durationpb.Duration   `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStatsRequest) Reset() {
	*x = GetClusterStatsRequest{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStatsRequest) ProtoMessage() {}

func (x *GetClusterStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStatsRequest.ProtoReflect.Descriptor instead.
func (*GetClusterStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{17}
}

func (x *GetClusterStatsRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *GetClusterStatsRequest) GetWindow() *durationpb.Duration {
	if x != nil {
		return x.Window
	}
	return nil
}

type StateCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         TaskState              `protobuf:"varint,1,opt,name=state,proto3,enum=orchestrator.v1.TaskState" json:"state,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateCount) Reset() {
	*x = StateCount{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateCount) ProtoMessage() {}

func (x *StateCount) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateCount.ProtoReflect.Descriptor instead.
func (*StateCount) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{18}
}

func (x *StateCount) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *StateCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetClusterStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AsOf               *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	Window             *durationpb.Duration   `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	ActiveWorkers      int64                  `protobuf:"varint,3,opt,name=active_workers,json=activeWorkers,proto3" json:"active_workers,omitempty"`
	OverdueTasks       int64                  `protobuf:"varint,4,opt,name=overdue_tasks,json=overdueTasks,proto3" json:"overdue_tasks,omitempty"`
	CurrentStateCounts []*StateCount          `protobuf:"bytes,5,rep,name=current_state_counts,json=currentStateCounts,proto3" json:"current_state_counts,omitempty"`
	CompletedInWindow  int64                  `protobuf:"varint,6,opt,name=completed_in_window,json=completedInWindow,proto3" json:"completed_in_window,omitempty"`
	FailedInWindow     int64                  `protobuf:"varint,7,opt,name=failed_in_window,json=failedInWindow,proto3" json:"failed_in_window,omitempty"`
	CancelledInWindow  int64                  `protobuf:"varint,8,opt,name=cancelled_in_window,json=cancelledInWindow,proto3" json:"cancelled_in_window,omitempty"`
	RetriedInWindow    int64                  `protobuf:"varint,9,opt,name=retried_in_window,json=retriedInWindow,proto3" json:"retried_in_window,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetClusterStatsResponse) Reset() {
	*x = GetClusterStatsResponse{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStatsResponse) ProtoMessage() {}

func (x *GetClusterStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStatsResponse.ProtoReflect.Descriptor instead.
func (*GetClusterStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{19}
}

func (x *GetClusterStatsResponse) GetAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOf
	}
	return nil
}

func (x *GetClusterStatsResponse) GetWindow() *durationpb.Duration {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *GetClusterStatsResponse) GetActiveWorkers() int64 {
	if x != nil {
		return x.ActiveWorkers
	}
	return 0
}

func (x *GetClusterStatsResponse) GetOverdueTasks() int64 {
	if x != nil {
		return x.OverdueTasks
	}
	return 0
}

func (x *GetClusterStatsResponse) GetCurrentStateCounts() []*StateCount {
	if x != nil {
		return x.CurrentStateCounts
	}
	return nil
}

func (x *GetClusterStatsResponse) GetCompletedInWindow() int64 {
	if x != nil {
		return x.CompletedInWindow
	}
	return 0
}

func (x *GetClusterStatsResponse) GetFailedInWindow() int64 {
	if x != nil {
		return x.FailedInWindow
	}
	return 0
}

func (x *GetClusterStatsResponse) GetCancelledInWindow() int64 {
	if x != nil {
		return x.CancelledInWindow
	}
	return 0
}

func (x *GetClusterStatsResponse) GetRetriedInWindow() int64 {
	if x != nil {
		return x.RetriedInWindow
	}
	return 0
}

type ListTaskLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaskLogsRequest) Reset() {
	*x = ListTaskLogsRequest{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskLogsRequest) ProtoMessage() {}

func (x *ListTaskLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskLogsRequest.ProtoReflect.Descriptor instead.
func (*ListTaskLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{20}
}

func (x *ListTaskLogsRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *ListTaskLogsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ListTaskLogsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTaskLogsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type TaskLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int64                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         LogLevel               `protobuf:"varint,3,opt,name=level,proto3,enum=orchestrator.v1.LogLevel" json:"level,omitempty"`
	Component     string                 `protobuf:"bytes,4,opt,name=component,proto3" json:"component,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLogEntry) Reset() {
	*x = TaskLogEntry{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLogEntry) ProtoMessage() {}

func (x *TaskLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLogEntry.ProtoReflect.Descriptor instead.
func (*TaskLogEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{21}
}

func (x *TaskLogEntry) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *TaskLogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TaskLogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *TaskLogEntry) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *TaskLogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskLogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ListTaskLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*TaskLogEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaskLogsResponse) Reset() {
	*x = ListTaskLogsResponse{}
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskLogsResponse) ProtoMessage() {}

func (x *ListTaskLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskLogsResponse.ProtoReflect.Descriptor instead.
func (*ListTaskLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP(), []int{22}
}

func (x *ListTaskLogsResponse) GetEntries() []*TaskLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListTaskLogsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListTaskLogsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_api_proto_orchestrator_v1_control_plane_proto protoreflect.FileDescriptor

const file_api_proto_orchestrator_v1_control_plane_proto_rawDesc = "" +
	"\n" +
	"-api/proto/orchestrator/v1/control_plane.proto\x12\x0forchestrator.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"G\n" +
	"\x05Scope\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fnamespace_id\x18\x02 \x01(\tR\vnamespaceId\"k\n" +
	"\tTimeRange\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"\xdd\x05\n" +
	"\x04Task\x12,\n" +
	"\x05scope\x18\x01 \x01(\v2\x16.orchestrator.v1.ScopeR\x05scope\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttask_type\x18\x03 \x01(\tR\btaskType\x120\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1a.orchestrator.v1.TaskStateR\x05state\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x16\n" +
	"\x06result\x18\x06 \x01(\fR\x06result\x12\x1b\n" +
	"\tworker_id\x18\a \x01(\tR\bworkerId\x12\x1f\n" +
	"\vretry_count\x18\b \x01(\x05R\n" +
	"retryCount\x12\x1f\n" +
	"\vmax_retries\x18\t \x01(\x05R\n" +
	"maxRetries\x121\n" +
	"\x06run_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x05runAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12@\n" +
	"\x0elast_failed_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\flastFailedAt\x12\x18\n" +
	"\aversion\x18\x0e \x01(\x03R\aversion\x12#\n" +
	"\rerror_message\x18\x0f \x01(\tR\ferrorMessage\x12E\n" +
	"\n" +
	"attributes\x18\x10 \x03(\v2%.orchestrator.v1.Task.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xea\x02\n" +
	"\n" +
	"TaskFilter\x122\n" +
	"\x06states\x18\x01 \x03(\x0e2\x1a.orchestrator.v1.TaskStateR\x06states\x12\x1d\n" +
	"\n" +
	"task_types\x18\x02 \x03(\tR\ttaskTypes\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12$\n" +
	"\x0etask_id_prefix\x18\x04 \x01(\tR\ftaskIdPrefix\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.orchestrator.v1.TimeRangeR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.orchestrator.v1.TimeRangeR\tupdatedAt\x121\n" +
	"\x06run_at\x18\a \x01(\v2\x1a.orchestrator.v1.TimeRangeR\x05runAt\x12\x1d\n" +
	"\n" +
	"text_query\x18\b \x01(\tR\ttextQuery\"~\n" +
	"\bTaskSort\x124\n" +
	"\x05field\x18\x01 \x01(\x0e2\x1e.orchestrator.v1.TaskSortFieldR\x05field\x12<\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x1e.orchestrator.v1.SortDirectionR\tdirection\"\xa9\x02\n" +
	"\x10ListTasksRequest\x12,\n" +
	"\x05scope\x18\x01 \x01(\v2\x16.orchestrator.v1.ScopeR\x05scope\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x123\n" +
	"\x06filter\x18\x04 \x01(\v2\x1b.orchestrator.v1.TaskFilterR\x06filter\x12-\n" +
	"\x04sort\x18\x05 \x01(\v2\x19.orchestrator.v1.TaskSortR\x04sort\x12'\n" +
	"\x0finclude_payload\x18\x06 \x01(\bR\x0eincludePayload\x12%\n" +
	"\x0einclude_result\x18\a \x01(\bR\rincludeResult\"\xe9\x01\n" +
	"\x11ListTasksResponse\x12+\n" +
	"\x05tasks\x18\x01 \x03(\v2\x15.orchestrator.v1.TaskR\x05tasks\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\x12?\n" +
	"\rsnapshot_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fsnapshotTime\x12*\n" +
	"\x11snapshot_event_id\x18\x05 \x01(\x03R\x0fsnapshotEventId\"\xa7\x01\n" +
	"\x0eGetTaskRequest\x12,\n" +
	"\x05scope\x18\x01 \x01(\v2\x16.orchestrator.v1.ScopeR\x05scope\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12'\n" +
	"\x0finclude_payload\x18\x03 \x01(\bR\x0eincludePayload\x12%\n" +
	"\x0einclude_result\x18\x04 \x01(\bR\rincludeResult\"<\n" +
	"\x0fGetTaskResponse\x12)\n" +
	"\x04task\x18\x01 \x01(\v2\x15.orchestrator.v1.TaskR\x04task\"\x9c\x01\n" +
	"\x0fTaskEventFilter\x122\n" +
	"\x06states\x18\x01 \x03(\x0e2\x1a.orchestrator.v1.TaskStateR\x06states\x12\x1d\n" +
	"\n" +
	"task_types\x18\x02 \x03(\tR\ttaskTypes\x12\x19\n" +
	"\btask_ids\x18\x03 \x03(\tR\ataskIds\x12\x1b\n" +
	"\tworker_id\x18\x04 \x01(\tR\bworkerId\"\xf5\x02\n" +
	"\x17StreamTaskEventsRequest\x12,\n" +
	"\x05scope\x18\x01 \x01(\v2\x16.orchestrator.v1.ScopeR\x05scope\x128\n" +
	"\x06filter\x18\x02 \x01(\v2 .orchestrator.v1.TaskEventFilterR\x06filter\x12#\n" +
	"\fresume_token\x18\x03 \x01(\tH\x00R\vresumeToken\x12&\n" +
	"\x0eafter_event_id\x18\x04 \x01(\x03H\x00R\fafterEventId\x12$\n" +
	"\x0emax_batch_size\x18\x05 \x01(\x05R\fmaxBatchSize\x128\n" +
	"\x18include_current_snapshot\x18\x06 \x01(\bR\x16includeCurrentSnapshot\x122\n" +
	"\x15include_task_snapshot\x18\a \x01(\bR\x13includeTaskSnapshotB\x11\n" +
	"\x0fresume_position\"\x81\x04\n" +
	"\tTaskEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12=\n" +
	"\n" +
	"event_type\x18\x03 \x01(\x0e2\x1e.orchestrator.v1.TaskEventTypeR\teventType\x12,\n" +
	"\x05scope\x18\x04 \x01(\v2\x16.orchestrator.v1.ScopeR\x05scope\x12\x17\n" +
	"\atask_id\x18\x05 \x01(\tR\x06taskId\x12A\n" +
	"\x0eprevious_state\x18\x06 \x01(\x0e2\x1a.orchestrator.v1.TaskStateR\rpreviousState\x12?\n" +
	"\rcurrent_state\x18\a \x01(\x0e2\x1a.orchestrator.v1.TaskStateR\fcurrentState\x12!\n" +
	"\ftask_version\x18\b \x01(\x03R\vtaskVersion\x12\x1b\n" +
	"\tworker_id\x18\t \x01(\tR\bworkerId\x12\x16\n" +
	"\x06reason\x18\n" +
	" \x01(\tR\x06reason\x12:\n" +
	"\rtask_snapshot\x18\v \x01(\v2\x15.orchestrator.v1.TaskR\ftaskSnapshot\"\xb1\x01\n" +
	"\x18StreamTaskEventsResponse\x122\n" +
	"\x06events\x18\x01 \x03(\v2\x1a.orchestrator.v1.TaskEventR\x06events\x12*\n" +
	"\x11next_resume_token\x18\x02 \x01(\tR\x0fnextResumeToken\x125\n" +
	"\x17high_watermark_event_id\x18\x03 \x01(\x03R\x14highWatermarkEventId\"\xbc\x01\n" +
	"\x11CancelTaskRequest\x12,\n" +
	"\x05scope\x18\x01 \x01(\v2\x16.orchestrator.v1.ScopeR\x05scope\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12)\n" +
	"\x10expected_version\x18\x05 \x01(\x03R\x0fexpectedVersion\"\x86\x01\n" +
	"\x12CancelTaskResponse\x12)\n" +
	"\x04task\x18\x01 \x01(\v2\x15.orchestrator.v1.TaskR\x04task\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12)\n" +
	"\x10already_terminal\x18\x03 \x01(\bR\x0falreadyTerminal\"\xff\x01\n" +
	"\x10RetryTaskRequest\x12,\n" +
	"\x05scope\x18\x01 \x01(\v2\x16.orchestrator.v1.ScopeR\x05scope\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12B\n" +
	"\x0frun_at_override\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rrunAtOverride\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12)\n" +
	"\x10expected_version\x18\x06 \x01(\x03R\x0fexpectedVersion\"Z\n" +
	"\x11RetryTaskResponse\x12)\n" +
	"\x04task\x18\x01 \x01(\v2\x15.orchestrator.v1.TaskR\x04task\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\"y\n" +
	"\x16GetClusterStatsRequest\x12,\n" +
	"\x05scope\x18\x01 \x01(\v2\x16.orchestrator.v1.ScopeR\x05scope\x121\n" +
	"\x06window\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x06window\"T\n" +
	"\n" +
	"StateCount\x120\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1a.orchestrator.v1.TaskStateR\x05state\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\xce\x03\n" +
	"\x17GetClusterStatsResponse\x12/\n" +
	"\x05as_of\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04asOf\x121\n" +
	"\x06window\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x06window\x12%\n" +
	"\x0eactive_workers\x18\x03 \x01(\x03R\ractiveWorkers\x12#\n" +
	"\roverdue_tasks\x18\x04 \x01(\x03R\foverdueTasks\x12M\n" +
	"\x14current_state_counts\x18\x05 \x03(\v2\x1b.orchestrator.v1.StateCountR\x12currentStateCounts\x12.\n" +
	"\x13completed_in_window\x18\x06 \x01(\x03R\x11completedInWindow\x12(\n" +
	"\x10failed_in_window\x18\a \x01(\x03R\x0efailedInWindow\x12.\n" +
	"\x13cancelled_in_window\x18\b \x01(\x03R\x11cancelledInWindow\x12*\n" +
	"\x11retried_in_window\x18\t \x01(\x03R\x0fretriedInWindow\"\x91\x01\n" +
	"\x13ListTaskLogsRequest\x12,\n" +
	"\x05scope\x18\x01 \x01(\v2\x16.orchestrator.v1.ScopeR\x05scope\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\"\xcb\x02\n" +
	"\fTaskLogEntry\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x03R\bsequence\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12/\n" +
	"\x05level\x18\x03 \x01(\x0e2\x19.orchestrator.v1.LogLevelR\x05level\x12\x1c\n" +
	"\tcomponent\x18\x04 \x01(\tR\tcomponent\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12A\n" +
	"\x06fields\x18\x06 \x03(\v2).orchestrator.v1.TaskLogEntry.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x01\n" +
	"\x14ListTaskLogsResponse\x127\n" +
	"\aentries\x18\x01 \x03(\v2\x1d.orchestrator.v1.TaskLogEntryR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore*\xbc\x01\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATE_PENDING\x10\x01\x12\x18\n" +
	"\x14TASK_STATE_SCHEDULED\x10\x02\x12\x16\n" +
	"\x12TASK_STATE_RUNNING\x10\x03\x12\x18\n" +
	"\x14TASK_STATE_COMPLETED\x10\x04\x12\x15\n" +
	"\x11TASK_STATE_FAILED\x10\x05\x12\x18\n" +
	"\x14TASK_STATE_CANCELLED\x10\x06*\x8c\x01\n" +
	"\rTaskSortField\x12\x1f\n" +
	"\x1bTASK_SORT_FIELD_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTASK_SORT_FIELD_CREATED_AT\x10\x01\x12\x1e\n" +
	"\x1aTASK_SORT_FIELD_UPDATED_AT\x10\x02\x12\x1a\n" +
	"\x16TASK_SORT_FIELD_RUN_AT\x10\x03*`\n" +
	"\rSortDirection\x12\x1e\n" +
	"\x1aSORT_DIRECTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SORT_DIRECTION_ASC\x10\x01\x12\x17\n" +
	"\x13SORT_DIRECTION_DESC\x10\x02*\xfa\x01\n" +
	"\rTaskEventType\x12\x1f\n" +
	"\x1bTASK_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TASK_EVENT_TYPE_CREATED\x10\x01\x12!\n" +
	"\x1dTASK_EVENT_TYPE_STATE_CHANGED\x10\x02\x12\x1b\n" +
	"\x17TASK_EVENT_TYPE_RETRIED\x10\x03\x12$\n" +
	" TASK_EVENT_TYPE_CANCEL_REQUESTED\x10\x04\x12&\n" +
	"\"TASK_EVENT_TYPE_ASSIGNMENT_CHANGED\x10\x05\x12\x1d\n" +
	"\x19TASK_EVENT_TYPE_HEARTBEAT\x10\x06*w\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x042\x90\x05\n" +
	"\x13ControlPlaneService\x12R\n" +
	"\tListTasks\x12!.orchestrator.v1.ListTasksRequest\x1a\".orchestrator.v1.ListTasksResponse\x12L\n" +
	"\aGetTask\x12\x1f.orchestrator.v1.GetTaskRequest\x1a .orchestrator.v1.GetTaskResponse\x12i\n" +
	"\x10StreamTaskEvents\x12(.orchestrator.v1.StreamTaskEventsRequest\x1a).orchestrator.v1.StreamTaskEventsResponse0\x01\x12U\n" +
	"\n" +
	"CancelTask\x12\".orchestrator.v1.CancelTaskRequest\x1a#.orchestrator.v1.CancelTaskResponse\x12R\n" +
	"\tRetryTask\x12!.orchestrator.v1.RetryTaskRequest\x1a\".orchestrator.v1.RetryTaskResponse\x12d\n" +
	"\x0fGetClusterStats\x12'.orchestrator.v1.GetClusterStatsRequest\x1a(.orchestrator.v1.GetClusterStatsResponse\x12[\n" +
	"\fListTaskLogs\x12$.orchestrator.v1.ListTaskLogsRequest\x1a%.orchestrator.v1.ListTaskLogsResponseBMZKgithub.com/manenim/task-orchestrator/pkg/api/orchestrator/v1;orchestratorv1b\x06proto3"

var (
	file_api_proto_orchestrator_v1_control_plane_proto_rawDescOnce sync.Once
	file_api_proto_orchestrator_v1_control_plane_proto_rawDescData []byte
)

func file_api_proto_orchestrator_v1_control_plane_proto_rawDescGZIP() []byte {
	file_api_proto_orchestrator_v1_control_plane_proto_rawDescOnce.Do(func() {
		file_api_proto_orchestrator_v1_control_plane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_orchestrator_v1_control_plane_proto_rawDesc), len(file_api_proto_orchestrator_v1_control_plane_proto_rawDesc)))
	})
	return file_api_proto_orchestrator_v1_control_plane_proto_rawDescData
}

var file_api_proto_orchestrator_v1_control_plane_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_api_proto_orchestrator_v1_control_plane_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_proto_orchestrator_v1_control_plane_proto_goTypes = []any{
	(TaskState)(0),                   // 0: orchestrator.v1.TaskState
	(TaskSortField)(0),               // 1: orchestrator.v1.TaskSortField
	(SortDirection)(0),               // 2: orchestrator.v1.SortDirection
	(TaskEventType)(0),               // 3: orchestrator.v1.TaskEventType
	(LogLevel)(0),                    // 4: orchestrator.v1.LogLevel
	(*Scope)(nil),                    // 5: orchestrator.v1.Scope
	(*TimeRange)(nil),                // 6: orchestrator.v1.TimeRange
	(*Task)(nil),                     // 7: orchestrator.v1.Task
	(*TaskFilter)(nil),               // 8: orchestrator.v1.TaskFilter
	(*TaskSort)(nil),                 // 9: orchestrator.v1.TaskSort
	(*ListTasksRequest)(nil),         // 10: orchestrator.v1.ListTasksRequest
	(*ListTasksResponse)(nil),        // 11: orchestrator.v1.ListTasksResponse
	(*GetTaskRequest)(nil),           // 12: orchestrator.v1.GetTaskRequest
	(*GetTaskResponse)(nil),          // 13: orchestrator.v1.GetTaskResponse
	(*TaskEventFilter)(nil),          // 14: orchestrator.v1.TaskEventFilter
	(*StreamTaskEventsRequest)(nil),  // 15: orchestrator.v1.StreamTaskEventsRequest
	(*TaskEvent)(nil),                // 16: orchestrator.v1.TaskEvent
	(*StreamTaskEventsResponse)(nil), // 17: orchestrator.v1.StreamTaskEventsResponse
	(*CancelTaskRequest)(nil),        // 18: orchestrator.v1.CancelTaskRequest
	(*CancelTaskResponse)(nil),       // 19: orchestrator.v1.CancelTaskResponse
	(*RetryTaskRequest)(nil),         // 20: orchestrator.v1.RetryTaskRequest
	(*RetryTaskResponse)(nil),        // 21: orchestrator.v1.RetryTaskResponse
	(*GetClusterStatsRequest)(nil),   // 22: orchestrator.v1.GetClusterStatsRequest
	(*StateCount)(nil),               // 23: orchestrator.v1.StateCount
	(*GetClusterStatsResponse)(nil),  // 24: orchestrator.v1.GetClusterStatsResponse
	(*ListTaskLogsRequest)(nil),      // 25: orchestrator.v1.ListTaskLogsRequest
	(*TaskLogEntry)(nil),             // 26: orchestrator.v1.TaskLogEntry
	(*ListTaskLogsResponse)(nil),     // 27: orchestrator.v1.ListTaskLogsResponse
	nil,                              // 28: orchestrator.v1.Task.AttributesEntry
	nil,                              // 29: orchestrator.v1.TaskLogEntry.FieldsEntry
	(*timestamppb.Timestamp)(nil),    // 30: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),      // 31: google.protobuf.Duration
}
var file_api_proto_orchestrator_v1_control_plane_proto_depIdxs = []int32{
	30, // 0: orchestrator.v1.TimeRange.start:type_name -> google.protobuf.Timestamp
	30, // 1: orchestrator.v1.TimeRange.end:type_name -> google.protobuf.Timestamp
	5,  // 2: orchestrator.v1.Task.scope:type_name -> orchestrator.v1.Scope
	0,  // 3: orchestrator.v1.Task.state:type_name -> orchestrator.v1.TaskState
	30, // 4: orchestrator.v1.Task.run_at:type_name -> google.protobuf.Timestamp
	30, // 5: orchestrator.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	30, // 6: orchestrator.v1.Task.updated_at:type_name -> google.protobuf.Timestamp
	30, // 7: orchestrator.v1.Task.last_failed_at:type_name -> google.protobuf.Timestamp
	28, // 8: orchestrator.v1.Task.attributes:type_name -> orchestrator.v1.Task.AttributesEntry
	0,  // 9: orchestrator.v1.TaskFilter.states:type_name -> orchestrator.v1.TaskState
	6,  // 10: orchestrator.v1.TaskFilter.created_at:type_name -> orchestrator.v1.TimeRange
	6,  // 11: orchestrator.v1.TaskFilter.updated_at:type_name -> orchestrator.v1.TimeRange
	6,  // 12: orchestrator.v1.TaskFilter.run_at:type_name -> orchestrator.v1.TimeRange
	1,  // 13: orchestrator.v1.TaskSort.field:type_name -> orchestrator.v1.TaskSortField
	2,  // 14: orchestrator.v1.TaskSort.direction:type_name -> orchestrator.v1.SortDirection
	5,  // 15: orchestrator.v1.ListTasksRequest.scope:type_name -> orchestrator.v1.Scope
	8,  // 16: orchestrator.v1.ListTasksRequest.filter:type_name -> orchestrator.v1.TaskFilter
	9,  // 17: orchestrator.v1.ListTasksRequest.sort:type_name -> orchestrator.v1.TaskSort
	7,  // 18: orchestrator.v1.ListTasksResponse.tasks:type_name -> orchestrator.v1.Task
	30, // 19: orchestrator.v1.ListTasksResponse.snapshot_time:type_name -> google.protobuf.Timestamp
	5,  // 20: orchestrator.v1.GetTaskRequest.scope:type_name -> orchestrator.v1.Scope
	7,  // 21: orchestrator.v1.GetTaskResponse.task:type_name -> orchestrator.v1.Task
	0,  // 22: orchestrator.v1.TaskEventFilter.states:type_name -> orchestrator.v1.TaskState
	5,  // 23: orchestrator.v1.StreamTaskEventsRequest.scope:type_name -> orchestrator.v1.Scope
	14, // 24: orchestrator.v1.StreamTaskEventsRequest.filter:type_name -> orchestrator.v1.TaskEventFilter
	30, // 25: orchestrator.v1.TaskEvent.occurred_at:type_name -> google.protobuf.Timestamp
	3,  // 26: orchestrator.v1.TaskEvent.event_type:type_name -> orchestrator.v1.TaskEventType
	5,  // 27: orchestrator.v1.TaskEvent.scope:type_name -> orchestrator.v1.Scope
	0,  // 28: orchestrator.v1.TaskEvent.previous_state:type_name -> orchestrator.v1.TaskState
	0,  // 29: orchestrator.v1.TaskEvent.current_state:type_name -> orchestrator.v1.TaskState
	7,  // 30: orchestrator.v1.TaskEvent.task_snapshot:type_name -> orchestrator.v1.Task
	16, // 31: orchestrator.v1.StreamTaskEventsResponse.events:type_name -> orchestrator.v1.TaskEvent
	5,  // 32: orchestrator.v1.CancelTaskRequest.scope:type_name -> orchestrator.v1.Scope
	7,  // 33: orchestrator.v1.CancelTaskResponse.task:type_name -> orchestrator.v1.Task
	5,  // 34: orchestrator.v1.RetryTaskRequest.scope:type_name -> orchestrator.v1.Scope
	30, // 35: orchestrator.v1.RetryTaskRequest.run_at_override:type_name -> google.protobuf.Timestamp
	7,  // 36: orchestrator.v1.RetryTaskResponse.task:type_name -> orchestrator.v1.Task
	5,  // 37: orchestrator.v1.GetClusterStatsRequest.scope:type_name -> orchestrator.v1.Scope
	31, // 38: orchestrator.v1.GetClusterStatsRequest.window:type_name -> google.protobuf.Duration
	0,  // 39: orchestrator.v1.StateCount.state:type_name -> orchestrator.v1.TaskState
	30, // 40: orchestrator.v1.GetClusterStatsResponse.as_of:type_name -> google.protobuf.Timestamp
	31, // 41: orchestrator.v1.GetClusterStatsResponse.window:type_name -> google.protobuf.Duration
	23, // 42: orchestrator.v1.GetClusterStatsResponse.current_state_counts:type_name -> orchestrator.v1.StateCount
	5,  // 43: orchestrator.v1.ListTaskLogsRequest.scope:type_name -> orchestrator.v1.Scope
	30, // 44: orchestrator.v1.TaskLogEntry.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 45: orchestrator.v1.TaskLogEntry.level:type_name -> orchestrator.v1.LogLevel
	29, // 46: orchestrator.v1.TaskLogEntry.fields:type_name -> orchestrator.v1.TaskLogEntry.FieldsEntry
	26, // 47: orchestrator.v1.ListTaskLogsResponse.entries:type_name -> orchestrator.v1.TaskLogEntry
	10, // 48: orchestrator.v1.ControlPlaneService.ListTasks:input_type -> orchestrator.v1.ListTasksRequest
	12, // 49: orchestrator.v1.ControlPlaneService.GetTask:input_type -> orchestrator.v1.GetTaskRequest
	15, // 50: orchestrator.v1.ControlPlaneService.StreamTaskEvents:input_type -> orchestrator.v1.StreamTaskEventsRequest
	18, // 51: orchestrator.v1.ControlPlaneService.CancelTask:input_type -> orchestrator.v1.CancelTaskRequest
	20, // 52: orchestrator.v1.ControlPlaneService.RetryTask:input_type -> orchestrator.v1.RetryTaskRequest
	22, // 53: orchestrator.v1.ControlPlaneService.GetClusterStats:input_type -> orchestrator.v1.GetClusterStatsRequest
	25, // 54: orchestrator.v1.ControlPlaneService.ListTaskLogs:input_type -> orchestrator.v1.ListTaskLogsRequest
	11, // 55: orchestrator.v1.ControlPlaneService.ListTasks:output_type -> orchestrator.v1.ListTasksResponse
	13, // 56: orchestrator.v1.ControlPlaneService.GetTask:output_type -> orchestrator.v1.GetTaskResponse
	17, // 57: orchestrator.v1.ControlPlaneService.StreamTaskEvents:output_type -> orchestrator.v1.StreamTaskEventsResponse
	19, // 58: orchestrator.v1.ControlPlaneService.CancelTask:output_type -> orchestrator.v1.CancelTaskResponse
	21, // 59: orchestrator.v1.ControlPlaneService.RetryTask:output_type -> orchestrator.v1.RetryTaskResponse
	24, // 60: orchestrator.v1.ControlPlaneService.GetClusterStats:output_type -> orchestrator.v1.GetClusterStatsResponse
	27, // 61: orchestrator.v1.ControlPlaneService.ListTaskLogs:output_type -> orchestrator.v1.ListTaskLogsResponse
	55, // [55:62] is the sub-list for method output_type
	48, // [48:55] is the sub-list for method input_type
	48, // [48:48] is the sub-list for extension type_name
	48, // [48:48] is the sub-list for extension extendee
	0,  // [0:48] is the sub-list for field type_name
}

func init() { file_api_proto_orchestrator_v1_control_plane_proto_init() }
func file_api_proto_orchestrator_v1_control_plane_proto_init() {
	if File_api_proto_orchestrator_v1_control_plane_proto != nil {
		return
	}
	file_api_proto_orchestrator_v1_control_plane_proto_msgTypes[10].OneofWrappers = []any{
		(*StreamTaskEventsRequest_ResumeToken)(nil),
		(*StreamTaskEventsRequest_AfterEventId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_orchestrator_v1_control_plane_proto_rawDesc), len(file_api_proto_orchestrator_v1_control_plane_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_orchestrator_v1_control_plane_proto_goTypes,
		DependencyIndexes: file_api_proto_orchestrator_v1_control_plane_proto_depIdxs,
		EnumInfos:         file_api_proto_orchestrator_v1_control_plane_proto_enumTypes,
		MessageInfos:      file_api_proto_orchestrator_v1_control_plane_proto_msgTypes,
	}.Build()
	File_api_proto_orchestrator_v1_control_plane_proto = out.File
	file_api_proto_orchestrator_v1_control_plane_proto_goTypes = nil
	file_api_proto_orchestrator_v1_control_plane_proto_depIdxs = nil
}
